********************************************************************
Filename: ADAE

Author: Ali

Date: 25jun2023

SAS: SAS 9.4 (TS2M0)

Platform: Windows 11

Project/Study: 

Description: <TO DEVELOP THE ADAE DATASETS>

Input: SDTM.AE, ADAM.ADSL

Output: ADAM.ADAE DATASET

Macros used: <No macros used>

-------------------------------------------------------------------------------

MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>

***************************************************************************/;
/* Bringing the raw datasets*/
libname raw 'E:\Ali_Clinical\RAW';
libname sdtm 'E:\Ali_Clinical\SAS BA BE_course\SDTM';
libname ADAM 'E:\Ali_Clinical\SAS BA BE_course\ADAM';

*******COPY ALL THE VARIABLES FROM ADSL****;
PROC SQL NOPRINT;
CREATE TABLE ADSL AS
SELECT * FROM ADAM.ADSL
ORDER BY USUBJID;
QUIT;

PROC SQL NOPRINT;
CREATE TABLE AE1 AS
SELECT * FROM SDTM.AE
ORDER BY USUBJID;
QUIT;


DATA AE2;
LENGTH STUDYID $20.;
MERGE AE1(IN=A) ADSL(IN=B);
BY USUBJID;
IF A AND B;
RUN;

******DATE IMPUTATIONS*****;
DATA ADAE0;
SET AE2;

TRTSDT=SUBSTR(TRT01SDTM,1, 10);
TRTEDT=SUBSTR(TRT02SDTM,1, 10);

/*YYYY-MM-DD*/

/*AESTDTC*/
IF LENGTH(AESTDTC) >=10 THEN DO;
AEST_YY=STRIP(SUBSTR(AESTDTC, 1, 4));
AEST_MM=STRIP(SUBSTR(AESTDTC, 6, 2));
AEST_DD=STRIP(SUBSTR(AESTDTC, 9, 2));
END;

ELSE IF LENGTH(AESTDTC)=7 THEN DO;
AEST_YY=STRIP(SUBSTR(AESTDTC, 1, 4));
AEST_MM=STRIP(SUBSTR(AESTDTC, 6, 2));
AEST_DD=' ';
END;

ELSE IF LENGTH(AESTDTC)=4 THEN DO;
AEST_YY=STRIP(SUBSTR(AESTDTC, 1, 4));
AEST_MM=' ';
AEST_DD=' ';
END;

/*AEENDTC*/
IF LENGTH(AEENDTC) >=10 THEN DO;
AEEN_YY=STRIP(SUBSTR(AEENDTC, 1, 4));
AEEN_MM=STRIP(SUBSTR(AEENDTC, 6, 2));
AEEN_DD=STRIP(SUBSTR(AEENDTC, 9, 2));
END;

ELSE IF LENGTH(AEENDTC)=7 THEN DO;
AEEN_YY=STRIP(SUBSTR(AEENDTC, 1, 4));
AEEN_MM=STRIP(SUBSTR(AEENDTC, 6, 2));
AEEN_DD=' ';
END;

ELSE IF LENGTH(AEENDTC)=4 THEN DO;
AEEN_YY=STRIP(SUBSTR(AEENDTC, 1, 4));
AEEN_MM=' ';
AEEN_DD=' ';
END;

/*TRTSDTC*/
TRTSDTC=STRIP(TRTSDT);

IF LENGTH(TRTSDTC) >=10 THEN DO;
TRST_YY=STRIP(SUBSTR(TRTSDTC, 1, 4));
TRST_MM=STRIP(SUBSTR(TRTSDTC, 6, 2));
TRST_DD=STRIP(SUBSTR(TRTSDTC, 9, 2));
END;

/*TRTEDTC*/
TRTEDTC=STRIP(TRTEDT);

IF LENGTH(TRTEDTC) >=10 THEN DO;
TREN_YY=STRIP(SUBSTR(TRTEDTC, 1, 4));
TREN_MM=STRIP(SUBSTR(TRTEDTC, 6, 2));
TREN_DD=STRIP(SUBSTR(TRTEDTC, 9, 2));
END;

/*If the partial date contains a different month */
/*from the date of first study dose, then */
/*impute it as the first day of the month. */

/*2018-04 DAY IS MISSING */

IF MISSING(AEST_DD) AND CMISS(AEST_YY, AEST_MM)=0 THEN DO;

IF AEST_MM=TRST_MM THEN AEST_DD=TRST_DD;
ELSE IF AEST_MM NE TRST_MM THEN AEST_DD="01";
ASTDTF='D';
END;

/*2018, MONTH AND DAY MISSING*/
IF CMISS(AEST_DD, AEST_MM)=2 AND NOT MISSING (AEST_YY) THEN DO;

IF AEST_YY=TRST_YY THEN DO;
AEST_MM=TRST_MM;
AEST_DD=TRST_DD;
ASTDTF='M';
END;
END;

ELSE IF AEST_YY NE TRST_YY THEN DO;
AEST_MM="12";
AEST_DD="31";
ASTDTF='M';
END;

/*YEAR AND DAY AND MONTH IS MISSING*/

ELSE IF CMISS(AEST_DD,AEST_MM,AEST_YY)=3 THEN DO;
AEST_DD=TRST_DD;
AEST_MM=TRST_MM;
AEST_YY=TRST_YY;
ASTDTF='Y';
END;

ASTDTC=CATX('-', STRIP(AEST_YY), STRIP(AEST_MM), STRIP(AEST_DD));
ASTDT=INPUT(ASTDTC, YYMMDD10.);

AENDTC=SUBSTR(AEENDTC,1, 10);
AENDT=INPUT(AENDTC, YYMMDD10.);

RUN;


DATA ADAE1;
SET ADAE0;

IF ASTDT NE . AND ASTDT >= TRTSDT THEN TRTMFL="Y";
ELSE TRTMFL="N";

IF TRTSDT <= ASTDT <= TRTEDT THEN DO;
APERIODC="PERIOD-01";
APERIOD=1;
END;

ELSE IF ASTDT >= TRTEDT THEN DO;
APERIODC="PERIOD-2";
APERIOD=2;
END;

IF APERIOD=1 THEN TRTA=TRT01A;
IF APERIOD=2 THEN TRTA=TRT02A;

RUN;


DATA ADAM.ADAE;
SET ADAE1;
RUN;
