********************************************************************
Filename: ADLB

Author: ALI

Date: 28 JUN 2020

SAS: SAS 9.4 (TS2M0)

Platform: Windows XP

Project/Study: 

Description: <TO DEVELOP THE ADLB DATASETS>

Input: SDTM.LB,ADAM.ADSL

Output ADLB

Macros used: <No macros used>

-------------------------------------------------------------------------------

MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>

***************************************************************************/;

/* Bringing the raw datasets*/
libname raw 'E:\Ali_Clinical\RAW';
libname sdtm 'E:\Ali_Clinical\SAS BA BE_course\SDTM';
libname ADAM 'E:\Ali_Clinical\SAS BA BE_course\ADAM';


********************COPY ALL THE VARIABLES FROM SDTM CORE DOMAIN*************;

PROC SQL NOPRINT;
CREATE TABLE LB1 AS
 SELECT * FROM SDTM.LB
 ORDER BY USUBJID;
 QUIT;

 
PROC SQL NOPRINT;
CREATE TABLE ADSL AS
 SELECT * FROM ADAM.ADSL
 ORDER BY USUBJID;
 QUIT;

 DATA LB2;
 MERGE ADSL (IN=A) LB1 (IN=B);
 BY USUBJID;
 IF A AND B;
 RUN;

 DATA LB3;
 SET LB2;

AVISIT = VISIT;
AVISITN = VISITNUM;

PARAM = STRIP (LBTEST) || "("|| STRIP (LBSTRESU)||")";

IF LBSTRESU EQ '' THEN DO;
PARAM = STRIP (LBTEST);
END;

PARAMCD = LBTESTCD;
PARCAT1=LBCAT;

IF PARCAT1="BIOCHEMISTRY" THEN PARCAT1N=1;
ELSE IF PARCAT1="HEAMATOLOGY" THEN PARCAT1N=2;
ELSE IF PARCAT1="URINALYSIS" THEN PARCAT1N=3;

RUN;

PROC SORT DATA=LB3 OUT=PARAM  (KEEP=PARAMCD) NODUPKEY;
BY PARAMCD;
RUN;
DATA PARAM;
SET PARAM;
PARAMN=_N_;
RUN;

PROC SORT DATA=LB3;BY PARAMCD;RUN;

DATA LB4;
MERGE LB3 (IN=A) PARAM (IN=B);
BY PARAMCD;
IF  A;
RUN;

PROC SORT DATA=LB4 OUT=LB5;
BY USUBJID PARCAT1N PARCAT1 PARAMN PARAM AVISITN AVISIT LBDTC;
RUN;


DATA LB6;
SET LB5;
BY USUBJID PARCAT1N PARCAT1  PARAMN PARAM AVISITN AVISIT  LBDTC;
RETAIN BASE SHIFT1;

FORMAT BASE AVAL CHG PCHG  BEST12.;



AVAL=LBSTRESN;
AVALC= PUT (LBSTRESN,BEST.);
AVALU=LBSTRESU;

IF FIRST.PARAMN THEN DO;
BASE=.;
END;

IF AVISITN=0 THEN DO;
BASE=AVAL;
ABLFL="Y";
SHIFT1=LBNRIND;
END;

IF BASE > . AND AVAL NE . THEN DO;
CHG=AVAL-BASE;
PCHG=(AVAL-BASE)/BASE*100;
END;

IF AVISIT="PERIOD-1" THEN DO;
TRTP=TRT01P; 
TRTPN=TRT01PN;
TRTA=TRT01A;
TRTAN=TRT01AN;
END;

IF AVISIT="PERIOD-2" THEN DO;
TRTP=TRT02P; 
TRTPN=TRT02PN;
TRTA=TRT02A;
TRTAN=TRT02AN;
END;


IF LENGTH (LBDTC)>=10 THEN ADT=INPUT (SUBSTR(LBDTC,1,10),YYMMDD10.);
IF LENGTH (LBDTC)>=19 THEN ADTM=INPUT (LBDTC,??IS8601DT.);
FORMAT ADTM DATETIME20.;

IF AVAL NE . THEN ANL01FL="Y";

IF AVISITN IN ( 0 1 ) THEN  DO; APERIODC='Period 01';APERIOD=1;END;
IF AVISITN GE 2  THEN  DO; APERIODC='Period 02';APERIOD=2;END;

ANRIND=LBNRIND;

If ANRIND = 'LOW' then ANRINDN = 1;
If ANRIND = 'NORMAL' then ANRINDN = 2;
If ANRIND = 'HIGH' then ANRINDN = 3;
If ANRIND = 'ABNORMAL' then ANRINDN = 4;

RUN;
DATA ADAM.ADLB;
SET LB6;
RUN;
