********************************************************************
Filename: DM

Author: Ali

Date: 21jun2023

SAS: SAS 9.4 (TS2M0)

Platform: Windows 11

Project/Study: 

Description: <TO DEVELOP THE ADSL DATASETS>

Input: SDTM.DM, SDTM.VS, SDTM.EX

Output: ADAM.ADSL DATASET

Macros used: <No macros used>

-------------------------------------------------------------------------------

MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>

***************************************************************************/;

/* Bringing the raw datasets*/
libname raw 'E:\Ali_Clinical\RAW';
libname sdtm 'E:\Ali_Clinical\SAS BA BE_course\SDTM';
libname ADAM 'E:\Ali_Clinical\SAS BA BE_course\ADAM';


/*COPY ALL VARIABLES FROM SDTM DM DOMAIN*/
PROC SQL NOPRINT;
CREATE TABLE DM1 AS
SELECT * FROM SDTM.DM
ORDER BY USUBJID;
QUIT;


/*SUPPDM*/
PROC TRANSPOSE DATA=SDTM.SUPPDM OUT=SUPPDMT (DROP=_NAME_ _LABEL_);
BY USUBJID;
ID QNAM;
VAR QVAL;
IDLABEL QLABEL;
RUN;

**********MERGE SUPPDM AND DM***************;
DATA DM2;
MERGE DM1(IN=A) SUPPDMT(IN=B);
BY USUBJID;
IF A;
RUN;


***********HT WT BMI********************;
DATA HEIGHT WEIGHT BMI;
SET SDTM.VS;
IF VSTESTCD="HEIGHT" THEN OUTPUT HEIGHT;
IF VSTESTCD="WEIGHT" THEN OUTPUT WEIGHT;
IF VSTESTCD="BMI" THEN OUTPUT BMI;
KEEP USUBJID VSSTRESN VSSTRESU;
RUN;


DATA HEIGHT;
SET HEIGHT;
HEIGHT=INPUT(VSSTRESN, BEST.);
HEIGHTU=VSSTRESU;
DROP VSSTRESN VSSTRESU;
RUN;

DATA WEIGHT;
SET WEIGHT;
WEIGHT=INPUT(VSSTRESN, BEST.);
WEIGHTU=VSSTRESU;
DROP VSSTRESN VSSTRESU;
RUN;

DATA BMI;
SET BMI;
BMI=INPUT(VSSTRESN, BEST.);
BMIU=VSSTRESU;
DROP VSSTRESN VSSTRESU;
RUN;

*************************MERGE DM2 HT WT BMI***************;
PROC SORT DATA=DM2; BY USUBJID; RUN;
PROC SORT DATA=HEIGHT; BY USUBJID; RUN;
PROC SORT DATA=WEIGHT; BY USUBJID; RUN;
PROC SORT DATA=BMI; BY USUBJID; RUN;

DATA DM3;
MERGE DM2(IN=A) HEIGHT WEIGHT BMI;
BY USUBJID;
IF A;
RUN;

*********GET THE EXPOSURE INFO*************;

DATA EX1;
SET SDTM.EX;
BY USUBJID;
IF FIRST.USUBJID;
KEEP USUBJID EXTRT EXDOSE EXSTDTC EXENDTC;
RUN;

DATA EX2 (RENAME=(EXTRT=EXTRT2 EXDOSE=EXDOSE2 EXSTDTC=EXSTDTC2 EXENDTC=EXENDTC2));
SET SDTM.EX;
BY USUBJID;
IF LAST.USUBJID;
KEEP USUBJID EXTRT EXDOSE EXSTDTC EXENDTC;
RUN;

/*MERGE DM3 EX1 EX2*/
DATA DM4;
MERGE DM3 (IN=A) EX1 EX2;
BY USUBJID;
IF A;
RUN;

DATA DM5;
SET DM4;

IF ARMCD="T-R" THEN DO;
TRT01P="Oxybutynin_TEST";
TRT01PN=1;
TRT02P="Oxybutynin_REFE";
TRT02PN=2;
END;

IF ARMCD="R-T" THEN DO;
TRT01P="Oxybutynin_REFE";
TRT01PN=2;
TRT02P="Oxybutynin_TEST";
TRT02PN=1;
END;

IF EXTRT="TEST" THEN DO;
TRT01A="Oxybutynin_TEST";
TRT01AN=1;
END;

IF EXTRT2="REFE" THEN DO;
TRT02A="Oxybutynin_REFE";
TRT02AN=2;
END;

IF EXTRT="REF" THEN DO;
TRT01A="Oxybutynin_REFE";
TRT01AN=2;
END;

IF EXTRT2="TEST" THEN DO;
TRT02A="Oxybutynin_TEST";
TRT02AN=1;
END;

TRT01SDTM=EXSTDTC;
TRT02SDTM=EXSTDTC2;

RUN;

DATA DM6;
SET DM5;

IF SEX="M" THEN SEXN=1;
ELSE IF SEX="F" THEN SEXN=2;

IF RACE="ASIAN" THEN RACEN=1;
ELSE IF RACE="OTHER" THEN RACEN=2;

If exdose ne . and exstdtc ne '' then SAFFL="Y";
else SAFFL="N";

IF ARMCD NE " " THEN ITTFL="Y";
ELSE ITTFL="N";

IF RFICDTC NE " " THEN ENRFL="Y";
ELSE ENRFL="N";

RUN;

DATA DM7;
SET DM6;
KEEP
STUDYID
USUBJID
SUBJID
SITEID
COUNTRY
INVNAM
RFICDTC
AGE
AGEU
SEX
SEXN
RACE
RACEN
RACEOTH
SAFFL
ITTFL
ARMCD
ARM
ENRFL
ACTARMCD 
ACTARM 
TRT01P
TRT01PN
TRT01A
TRT01AN
TRT02P
TRT02PN
TRT02A
TRT02AN
TRT01SDTM
TRT02SDTM
HEIGHT
WEIGHT
BMI
HEIGHTU
WEIGHTU
BMIU
;
RUN;

PROC SQL NOPRINT;
CREATE TABLE FINAL_ADSL AS

SELECT
STUDYID "Study Identifier" LENGTH=20,
USUBJID "Unique Subject Identifier"LENGTH=40,
SUBJID "Subject Identifier for the Study"LENGTH=40,
SITEID "Study Site Identifier"LENGTH=20,
COUNTRY "Country"LENGTH=3,
INVNAM "Investigator Name"LENGTH=60,
RFICDTC "Date of Informed Consent"LENGTH=19,
AGE "Age"LENGTH=8,
AGEU "Age Units"LENGTH=20,
SEX"Sex"LENGTH=1,
SEXN"Sex (N)"LENGTH=8,
RACE"Race"LENGTH=60,
RACEN""LENGTH=8,
RACEOTH"Race, Other"LENGTH=200,
SAFFL"Safety Population Flag"LENGTH=1,
ITTFL"Randomized Population Flag"LENGTH=1,
ARMCD"Planned Arm Code"LENGTH=20,
ARM"Description of Planned Arm"LENGTH=200,
ENRFL"Enrollment Population Flag"LENGTH=1,
ACTARMCD "Actual Arm Code "LENGTH=20,
ACTARM "Description of Actual Arm "LENGTH=200,
TRT01P"Planned Treatment for Period 01"LENGTH=40,
TRT01PN"Planned Treatment for Period 01 (N)"LENGTH=8,
TRT01A"Actual Treatment for Period 01"LENGTH=40,
TRT01AN"Actual Treatment for Period 01 (N)"LENGTH=8,
TRT02P"Planned Treatment for Period 02"LENGTH=40,
TRT02PN"Planned Treatment for Period 02 (N)"LENGTH=8,
TRT02A"Actual Treatment for Period 02"LENGTH=40,
TRT02AN"Actual Treatment for Period 02 (N)"LENGTH=8,
TRT01SDTM"Treatment start date/time Period 01"LENGTH=20,
TRT02SDTM"Treatment start date/time Period 02"LENGTH=20,
HEIGHT"Height"LENGTH=8,
WEIGHT"Weight"LENGTH=8,
BMI"BMI"LENGTH=8,
HEIGHTU"Height Unit"LENGTH=20,
WEIGHTU"Weight Unit"LENGTH=20,
BMIU"BMI Unit"LENGTH=20
FROM DM7;
QUIT;


DATA ADAM.ADSL (LABEL="SUBJECT-LEVEL ANALYSIS DATASET");
SET FINAL_ADSL;
RUN;





