

DATA VS1_;
SET RAW.DEMOG_RAW;
STUDYID=STRIP(STUDY);
DOMAIN="VS";
SUBJID=STRIP(SUBJID);
SITEID=STRIP(SITE);
USUBJID=STUDYID||"-"||SITEID||"-"||SUBJID;

VSDTC=PUT(ENRDT, IS8601DA.)||"T"||PUT(ENRTM, TOD8.);

VSTPT=" ";

IF VSTPT="Check-in" THEN VSTPTNUM=1;
ELSE IF VSTPT="0" THEN VSTPTNUM=2;
ELSE IF VSTPT="2" THEN VSTPTNUM=3;
ELSE IF VSTPT="8" THEN VSTPTNUM=4;
ELSE IF VSTPT="Check-out" THEN VSTPTNUM=5;

IF VISIT="SCREENING" THEN VISITNUM=0;
ELSE IF VISIT="PERIOD-1" THEN VISITNUM=1;
ELSE IF VISIT="PERIOD-2" THEN VISITNUM=2;

RUN;


/*DERIVING HT WT BMI*/
PROC SORT DATA=VS1_ OUT=VS2_;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
RUN;

/*TEST PARAMETERS*/
PROC TRANSPOSE DATA=VS2_ OUT=VS3_;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
VAR HT WT BMI;
RUN;

DATA VS4_;
SET VS3_;
LENGTH VSTESTCD $8. VSTEST$40.;
IF _NAME_="HT" THEN DO; VSTESTCD="HEIGHT"; VSTEST="HEIGHT"; END;
IF _NAME_="WT" THEN DO; VSTESTCD="WEIGHT"; VSTEST="WEIGHT"; END;
IF _NAME_="BMI" THEN DO; VSTESTCD="BMI"; VSTEST="BODY MASS INDEX"; END;


VSORRES=STRIP(PUT(COL1, BEST.));
VSSTRESN=VSORRES;
DROP COL1;
RUN;

/*HANDLING HTU WTU BMIU*/

PROC TRANSPOSE DATA=VS2_ OUT=VS33_;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
VAR HTU WTU BMIU;
RUN;

DATA VS44_;
SET VS33_;
LENGTH VSTESTCD $8. VSTEST$40.;
IF _NAME_="HTU" THEN DO; VSTESTCD="HEIGHT"; VSTEST="HEIGHT"; END;
IF _NAME_="WTU" THEN DO; VSTESTCD="WEIGHT"; VSTEST="WEIGHT"; END;
IF _NAME_="BMIU" THEN DO; VSTESTCD="BMI"; VSTEST="BODY MASS INDEX"; END;


VSORRESU=STRIP(COL1);
IF VSORRESU="CM" THEN VSORRESU="cm";
IF VSORRESU="KG" THEN VSORRESU="kg";
IF VSORRESU="KG/M2" THEN VSORRESU="kg/m2";
VSSTRESU=VSORRESU;

/*IF VSTESTCD="TEMP" THEN DO;*/
/*VSSTRESU="C";*/
/*END;*/
DROP COL1;
RUN;


/*MERGE VS4_ VS44_*/
PROC SORT DATA=VS4_; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;
PROC SORT DATA=VS44_; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;

DATA FINAL_DM;
MERGE VS4_ VS44_;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD;
RUN;
