********************************************************************
Filename: VS

Author: Ali

Date: 08jun2023

SAS: SAS 9.4 (TS2M0)

Platform: Windows 11

Project/Study: 

Description: <TO DEVELOP THE VS DATASETS>

Input: Vital_RAW,

Output SDTM VS DATASET

Macros used: <No macros used>

-------------------------------------------------------------------------------

MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>

***************************************************************************/;

/* Bringing the raw datasets*/
libname raw 'E:\Ali_Clinical\RAW';
libname sdtm 'E:\Ali_Clinical\SAS BA BE_course\SDTM';

DATA VS1;
SET RAW.VITAL_RAW;
STUDYID=STRIP(STUDYID);
DOMAIN="VS";
SUBJID=STRIP(SUBJID);
SITEID=STRIP(SITE);
USUBJID=STUDYID||"-"||SITEID||"-"||SUBJID;

VSDTC=PUT(RECDT, IS8601DA.)||"T"||PUT(RECDTM, TOD8.);


VSTPT=STRIP(TP);

IF VSTPT="Check-in" THEN VSTPTNUM=1;
ELSE IF VSTPT="0" THEN VSTPTNUM=2;
ELSE IF VSTPT="2" THEN VSTPTNUM=3;
ELSE IF VSTPT="8" THEN VSTPTNUM=4;
ELSE IF VSTPT="Check-out" THEN VSTPTNUM=5;

IF VISIT="SCREENING" THEN VISITNUM=0;
ELSE IF VISIT="PERIOD-1" THEN VISITNUM=1;
ELSE IF VISIT="PERIOD-2" THEN VISITNUM=2;

RUN;

PROC SORT DATA=VS1 OUT=VS2;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
RUN;

/*TEST PARAMETERS*/
PROC TRANSPOSE DATA=VS2 OUT=VS3;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
VAR PULSE TEMP SYS DIA;
RUN;

DATA VS4;
SET VS3;
LENGTH VSTESTCD $8. VSTEST$40.;
IF _NAME_="PULSE" THEN DO; VSTESTCD="PULSE"; VSTEST="PULSE RATE"; END;
IF _NAME_="TEMP" THEN DO; VSTESTCD="TEMP"; VSTEST="TEMPRATURE"; END;
IF _NAME_="SYS" THEN DO; VSTESTCD="SYSBP"; VSTEST="SYSTOLIC BLOOD PRESSURE"; END;
IF _NAME_="DIA" THEN DO; VSTESTCD="DIABP"; VSTEST="DIASTOLIC BLOOD PRESSURE"; END;

VSORRES=STRIP(PUT(COL1, BEST.));
VSSTRESN=VSORRES;
/*IF VSTESTCD="TEMP" THEN DO;*/
/*VSSTRESN=ROUND((COL1 - 32)* 5/9, 0.1); END;*/
/*VSSTRESC=PUT(VSSTRESN, BEST.);*/

DROP COL1;
RUN;

/*HANDLING UNITS*/

PROC TRANSPOSE DATA=VS2 OUT=VS33;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
VAR PULSEU TEMPU SYSU DIAU;
RUN;

DATA VS44;
SET VS33;
LENGTH VSTESTCD $8. VSTEST$40.;
IF _NAME_="PULSEU" THEN DO; VSTESTCD="PULSE"; VSTEST="PULSE RATE"; END;
IF _NAME_="TEMPU" THEN DO; VSTESTCD="TEMP"; VSTEST="TEMPRATURE"; END;
IF _NAME_="SYSU" THEN DO; VSTESTCD="SYSBP"; VSTEST="SYSTOLIC BLOOD PRESSURE"; END;
IF _NAME_="DIAU" THEN DO; VSTESTCD="DIABP"; VSTEST="DIASTOLIC BLOOD PRESSURE"; END;

VSORRESU=STRIP(COL1);
IF VSORRESU="per min" THEN VSORRESU="beats/min";
IF VSORRESU="mm of Hg" THEN VSORRESU="mmHg";

VSSTRESU=VSORRESU;

/*IF VSTESTCD="TEMP" THEN DO;*/
/*VSSTRESU="C";*/
/*END;*/
DROP COL1;
RUN;


/*HANDLING TEST RESULTS IN CHARACTERS*/

PROC TRANSPOSE DATA=VS2 OUT=VS333;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC;
VAR PULSER TEMPR SYSR DIAR;
RUN;

DATA VS444;
SET VS333;
LENGTH VSTESTCD $8. VSTEST$40.;
IF _NAME_="PULSER" THEN DO; VSTESTCD="PULSE"; VSTEST="PULSE RATE"; END;
IF _NAME_="TEMPR" THEN DO; VSTESTCD="TEMP"; VSTEST="TEMPRATURE"; END;
IF _NAME_="SYSR" THEN DO; VSTESTCD="SYSBP"; VSTEST="SYSTOLIC BLOOD PRESSURE"; END;
IF _NAME_="DIAR" THEN DO; VSTESTCD="DIABP"; VSTEST="DIASTOLIC BLOOD PRESSURE"; END;

VSSTRESC=STRIP(COL1);

DROP COL1;
RUN;


/*MERGE VS4 VS44 VS444*/

PROC SORT DATA=VS4; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;
PROC SORT DATA=VS44; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;
PROC SORT DATA=VS444; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;

DATA FINAL;
MERGE VS4 VS44 VS444;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD;
RUN;

DATA FINAL1;
SET FINAL;
IF VSTPT='0' THEN VSBLFL='Y';
ELSE VSBLFL=" ";
RUN;

/*COMBINING FINAL1 FINAL_DM*/
DATA FINAL2;
SET FINAL1 FINAL_DM ;
VSDTN=DATEPART(INPUT(VSDTC, IS8601DT.));
RUN;


/*STUDY DAY COLLECTION*/
DATA DM1;
SET SDTM.DM;
RFSTDTN=DATEPART(INPUT(RFSTDTC, IS8601DT.));
KEEP USUBJID RFSTDTN RFSTDTC; 
RUN;

/*MERGE DM1 AE2*/
PROC SORT DATA=DM1; BY USUBJID; RUN;
PROC SORT DATA=FINAL2; BY USUBJID; RUN;

DATA DM_VS;
MERGE DM1(IN=A) FINAL2(IN=B);
BY USUBJID;
IF A AND B;
RUN;

DATA DM_VS1;
SET DM_VS;

IF VSDTN > . AND RFSTDTN > . THEN DO;

IF VSDTN >= RFSTDTN THEN VSDY= VSDTN-RFSTDTN+1;
ELSE IF VSDTN < RFSTDTN THEN VSDY=VSDTN-RFSTDTN; END;

RUN;


PROC SORT DATA=DM_VS1; BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD; RUN;

DATA DM_VS2;
SET DM_VS1;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSTESTCD;
IF FIRST.USUBJID THEN VSSEQ=1;
ELSE VSSEQ+1;
RUN;

DATA DM_VS3;
SET DM_VS2;
KEEP STUDYID
DOMAIN
USUBJID
VSSEQ
VSTESTCD
VSTEST
VSORRES
VSORRESU
VSSTRESC
VSSTRESN
VSSTRESU
VSBLFL
VISITNUM
VISIT
VSDTC
VSDY
VSTPT
VSTPTNUM
; RUN;

PROC SQL;
CREATE TABLE FINAL_VS AS
SELECT
STUDYID"Study Identifier" LENGTH=8,
DOMAIN "Domain
Abbreviation" LENGTH=2,
USUBJID"Unique Subject Identifier" LENGTH=50,
VSSEQ"Sequence Number" LENGTH=8,
VSTESTCD"Vital Signs Test Short Name" LENGTH=8,
VSTEST"Vital Signs Test Name" LENGTH=40,
VSORRES"Result or Finding in Original Units" LENGTH=200,
VSORRESU"Original Units" LENGTH=40,
VSSTRESC"Character Result/Finding in Std Format" LENGTH=200,
VSSTRESN"Numeric Result/Finding in Standard Units" LENGTH=8,
VSSTRESU"Standard Units" LENGTH=40,
VSBLFL"Baseline Flag" LENGTH=25,
VISITNUM"Visit Number" LENGTH=8,
VISIT"Visit Name" LENGTH=100,
VSDTC"Date/Time of Measurements" LENGTH=20,
VSDY"Study Day of Vital Signs" LENGTH=8,
VSTPT"Planned Time Point Name" LENGTH=8,
VSTPTNUM"Planned Time Point Number" LENGTH=8
FROM DM_VS3;
RUN;

DATA SDTM.VS (LABEL="Vital Signs");
SET FINAL_VS;
RUN;

LIBNAME XPT XPORT "E:\Ali_Clinical\SAS BA BE_course\SDTM XPT\VS.XPT";
DATA XPT.VS;
SET SDTM.VS;
RUN;

